version: '3'
services:
  db:
    image: "microsoft/mssql-server-linux"
    environment:
      SA_PASSWORD: "YourStrongP@ssword"
      ACCEPT_EULA: "Y"
  web:
    build: ./UserLoginAPI/UserLoginAPI
    depends_on:
      - db
    expose:
      - "80"
    volumes:
      - "/machine_config:/app/machine_config"
    labels:
      - "SERVICE_80_NAME=Authentication"
      - "SERVICE_TAGS=AuthenticationTag"